version: 2.1
orbs:
  node: circleci/node@4.2.0
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    # Primary container image where all commands run

    docker:
      - image: circleci/python:3.6.2-stretch-browsers
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          TEST_DATABASE_URL: postgresql://root@localhost/circle_test
          
    # Service container image
    
      - image: circleci/postgres:9.6.5-alpine-ram
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run: 
          name: Front-End Install
          command: 
            npm run frontend:install 
      - run: 
          name: Back-End Install
          command: 
            npm run backend:install 
      - run: 
          name: Build Frontend
          command: npm run frontend:build
      - run: 
          name: Build Backend
          command: npm run backend:build
      - run: 
          name: Check for Updates 
          command: sudo apt-get update
       # Download postgreSQL client and set up table for testing
      - run: 
          name: Download PSQL Client
          command: sudo apt-get install postgresql-client-9.6
      - run: whoami
      - run: 
          name: Create DB table
          command: |
            psql \
            -d $TEST_DATABASE_URL \
            -c "CREATE TABLE images (id serial not null, title char(250), url char(500));"\  
      - run: 
        name: Run Jest Tests 
        command: npm run test

