version: 2.1
orbs:
  node: circleci/node@4.2.0
jobs:
  build:
    # Primary container image where all commands run

    docker:
      - image: circleci/python:3.6.2-stretch-browsers
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
          
    steps:
      - node/install
      - checkout
      - run: 
          name: Front-End Install
          command: 
            npm run frontend:install 
      - run: 
          name: Back-End Install
          command: 
            npm run backend:install 
