version: 2.1
orbs:
  node: circleci/node@4.2.0
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    # Primary container image where all commands run

    docker:
      - image: circleci/python:3.6.2-stretch-browsers
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          TEST_DATABASE_URL: postgresql://root@localhost/circle_test
          
    # Service container image
    
      - image: circleci/postgres:9.6.5-alpine-ram
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run: 
          name: Front-End Install
          command: 
            npm run frontend:install 
      - run: 
          name: Back-End Install
          command: 
            npm run backend:install 
      - run: npm install # install jest and dependencies for root
      - run: npm run frontend:build
      - run: npm run backend:build
      - run: sudo apt-get update
       # Download postgreSQL client and set up table for testing
      - run: sudo apt-get install postgresql-client-9.6
      - run: whoami
      - run: |
          psql \
          -d $TEST_DATABASE_URL \
          -c "CREATE TABLE images (id serial not null, title char(250), url char(500));"\  
      # - run: npm run test
      # - run: npm run frontend:deploy

